[package]
name = "recraft_render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
font8x8.workspace = true
glam.workspace = true
image.workspace = true
log.workspace = true
recraft_core = { path = "../recraft_core" }
recraft_protocol = { path = "../recraft_protocol" }
serde_json.workspace = true
thiserror.workspace = true
wgpu.workspace = true
winit.workspace = true
zip.workspace = true

[dev-dependencies]
pollster = "0.3"
