[package]
name = "recraft_app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
glam.workspace = true
log.workspace = true
pollster.workspace = true
recraft_core = { path = "../recraft_core" }
recraft_protocol = { path = "../recraft_protocol" }
recraft_render = { path = "../recraft_render" }
winit.workspace = true
